
INSERT INTO users (firstname, lastname, username, password, email) VALUES
('Xiaoming', 'Yang', 'xmyang', '12345', 'xiaomingyang@pursuit.org'),
('Sara', 'D''Arce', 'SaraDArce', '12345', 'saradarce@pursuit.org'),
('Larisa', 'Shapkina', 'lshapkina', '12345', 'larisashapking@pursuit.org'),
('Stephanie', 'Reyes', 'sreyes1089', '12345', 'stephaniereyes@pursuit.org'),
('John', 'Reez', 'maninasuit', '324234', 'jreez6742@nbc.com'),
('Sameen', 'Hsaw', 'xmyang', '9385733', 'sammhsaw@cbs.com'),
('Lionel', 'Fusco', 'goodcop', '937423462', 'lionfusco@cbs.com'),
('Tom', 'Anderson', 'tanderson', '342324582374', 'tanderson3721@gmail.com'),
('Harold', 'Finch', 'csgenius', '2343432', 'haroldf@gmail.com'),
('Joss', 'Carter', 'detective', '432353443', 'josscar@yahoo.com');



INSERT INTO listings (user_id, category, title, description, image) VALUES
('1', 'Electronics', 'Apple iPhone 5 16GB', 'Great shape', 'https://cdn.vox-cdn.com/thumbor/haJH385wK6DDCmMuadVJ96k66CU=/1400x1400/filters:format(jpeg)/cdn.vox-cdn.com/uploads/chorus_asset/file/12798851/iphone-5.1419973710.jpg'),
('1', 'Electronics', 'HP Chromebase 21.5" All-in-One', 'Desktop', 'https://m.media-amazon.com/images/I/81w3miL-DHL._AC_SX615_SY462_.jpg'),
('1', 'Electronics', 'Apple AirPods Pro', 'Adaptive EQ automatically tunes', 'https://m.media-amazon.com/images/I/71bhWgQK-cL._AC_SX425_.jpg'),
('1', 'Electronics', 'Rotary Corded Retro Phone - Black', 'Black', 'https://m.media-amazon.com/images/I/71zW3dWQgFS._AC_SX679_.jpg'),
('1', 'Electronics', 'Motorola T100 Talkabout Radio', '2 Pack', 'https://images-na.ssl-images-amazon.com/images/I/71bDU9VN4SL._AC._SR360,460.jpg'),
('1', 'Electronics', 'Corded Retro Phone', 'Black, Dialer Type: Rotary', 'https://m.media-amazon.com/images/I/8195Ls1ONHL._AC_SX679_.jpg'),
('1', 'Electronics', 'Retro Rotary Phone, Vintage Telephone Retro Phone', ' Resin, Metal, Battery Powered, Rotary', 'https://m.media-amazon.com/images/I/81WMhdtQtDL._AC_SX425_.jpg'),
('1', 'Electronics', 'Functional Gramophone', 'Handmade, brass, wood', 'https://i.etsystatic.com/21533901/r/il/2feb17/3169251742/il_794xN.3169251742_1pa4.jpg'),
('1', 'Electronics', 'Antique Original Working Gramophone', 'New', 'https://i.ebayimg.com/images/g/tnoAAOSwVAlg4AoV/s-l500.jpg'),
('1', 'Electronics', 'Antique Phonograph Gramophone', ' Wireless, Wired, Plastic', 'https://m.media-amazon.com/images/I/81x1yVp0ZOL._AC_SX425_.jpg'),
('1', 'Electronics', 'Antique Radio 3D Model', 'Desktop', 'https://www.renderhub.com/btvisuals/antique-radio-game-ready/antique-radio-game-ready-01.jpg'),
('1', 'Electronics', 'Bluetooth Speaker', ' Wireless, Bluetooth', 'https://m.media-amazon.com/images/I/81KUQ9V7IlS._AC_SX425_.jpg'),
('1', 'Toys', 'Vintage Barbie Dolls', 'Well loved and cared for', 'https://barbiedollmint.com/image/1960-s-Huge-Vintage-Barbie-Dolls-Lot-Clothes-Accessories-1960-s-Free-Shipping-02-hhd.jpg'),
('1', 'Toys', 'Building Toys for Toddlers', 'Well loved and cared for', 'https://m.media-amazon.com/images/I/81LjVUb4lfL._AC_UL320_.jpg'),
('2', 'Sports Memorabilia', 'SIGNED BASEBALL', 'Desirable condition', 'https://scontent-lga3-2.xx.fbcdn.net/v/t1.6435-9/131943100_10165476888425643_4835709211047916789_n.jpg?stp=dst-jpg_p720x720&_nc_cat=102&ccb=1-6&_nc_sid=b9115d&_nc_ohc=hI1dZnGzh44AX-2e7rJ&_nc_oc=AQl7PECUwAReKk25a6B2V3-WtZyziRms8rBK7zYk6KDZpCIeBWF57xPQvC4AASaG5qR2_wi7_HIGQmywEejP_pwN&tn=3dQlI0iHUKxfkZwA&_nc_ht=scontent-lga3-2.xx&oh=00_AT8JgYY7dZ7TIn8v_uq_23cJB0RbWd1hxk41ov97xQiccw&oe=62A315F7'),
('2', 'Toys', 'Universal Monster Studio 1992', 'Only half the monsters', 'https://thumbs.worthpoint.com/zoom/images1/1/0919/03/universal-studios-monsters-monster_1_ce5a695929fecefc7d8ce72ac49f774d.jpg'),
('2', 'Toys', 'Wonder Woman Kids Bandages', 'Wear Like Stickers', 'https://m.media-amazon.com/images/S/abs-image-upload-na/6/AmazonStores/ATVPDKIKX0DER/6b2d377bee59f5a2677cc8311fa38810.w750.h750._CR0%2C0%2C750%2C750_SX320_SY320_.jpg'),
('2', 'Electronics', 'Sony 28 Inch 4K Ultra HD TV X90K Series', 'BRAVIA XR Full Array LED Smart Google TV', 'https://m.media-amazon.com/images/I/81KOr7zrq-L._AC_SX425_.jpg'),
('2', 'Furniture', '5 Drawer Dresser Long Wide Chest of Drawers', 'Living Room, Bedroom, Hallway, Nursery, Kid', 'https://m.media-amazon.com/images/I/81YknWLq-pL._AC_SX569_.jpg'),
('2', 'Furniture', 'Used, Vintage, and Antique Furniture in NYC', 'Living Room', 'https://wp-tid.zillowstatic.com/streeteasy/2/antiquesofaFEAT-37341d.jpg'),
('2', 'Furniture', 'Nolany Convertible Sectional Sofa Set', 'Living Room, Wood, Dark Khaki', 'https://m.media-amazon.com/images/I/81SinP7w5AL._AC_SX425_.jpg'),
('2', 'Furniture', '76" Convertible Sleeper Sofa', 'Living Room, Small Space, Bedroom', 'https://m.media-amazon.com/images/I/715CdD8WnVL._AC_SX425_.jpg'),
('2', 'Furniture', 'Mid-Century Modern Tufted Leather Sofa Couch, 82"W', 'Cognac Leather, Mid-Century Modern', 'https://m.media-amazon.com/images/I/81lFsUzmTRL._AC_SX425_.jpg'),
('2', 'Furniture', 'Convertible Sectional Sofa Couch, (Dark Grey)', 'One Size, Dark Grey, Wood, Linen, Living Room', 'https://m.media-amazon.com/images/I/91VV-H0j9jL._AC_SX425_.jpg'),
('2', 'Furniture', 'Floor Bed, Daybed for Kids with Trundle Bed', 'Solid wood, Floor Bed', 'https://m.media-amazon.com/images/I/81GWCViSeqL._AC_SX679_.jpg'),
('2', 'Furniture', 'Red Accent Table', 'Red, Wood', 'https://m.media-amazon.com/images/I/91y0isVyuIL._SX500_.jpg'),
('2', 'Furniture', 'Manual Coffee Bean Grinder', 'Black, Stainless Steel', 'https://m.media-amazon.com/images/I/51SeFO-wp-L._AC_SX679_.jpg'),
('2', 'Furniture', 'Radiator Cover (Shaker)', 'MODERN STYLE, Maple Plywood', 'https://m.media-amazon.com/images/I/41uhiW2522L._SX500_.jpg'),
('2', 'Furniture', '40" Reclaimed Barn Beam Coffee Table', 'Living Room, 100 Year Old Beams', 'https://m.media-amazon.com/images/I/81Vd+Qut0BL._SY500_.jpg'),
('2', 'Furniture', 'House Bed Frame Full Size Made in the USA', 'Solid, furniture grade wood, no glues or plywoods', 'https://m.media-amazon.com/images/I/41JC8GwL71S.jpg'),
('2', 'Furniture', 'White Farmhouse Coffee Table with Shelf', 'white farmhouse, wood', 'https://m.media-amazon.com/images/I/91fqJAAmHLL._SX500_.jpg'),
('2', 'Furniture', 'Hillsdale Furniture Chesapeake Bed Set', 'Rustic Brown, Antique', 'https://m.media-amazon.com/images/I/91scWI-qyaL._AC_SX425_.jpg'),
('2', 'Furniture', 'Toddler Teepee Bed Handmade in the USA', 'MADE WITH PREMIUM, KNOT-FREE, LOCALLY HARVESTED POPLAR WOOD', 'https://m.media-amazon.com/images/I/91pdZhgTqWL._SY800_.jpg'),
('2', 'Furniture', 'Twin Full or Queen Size House Bed', 'Solid, furniture grade poplar wood, no glues or plywoods', 'https://m.media-amazon.com/images/I/71rxAQfMPpL._SX500_.jpg'),
('3', 'Furniture', 'Retro Chair', 'Very sturdy, could afford to be cleaned a bit', 'https://gapropsource.com/Pictures/18/PS001918.jpg'),
('3', 'Furniture', 'Furniture MDF 28mm Kit Chairs 8 Pack', 'Made in the USA Atomic Laser Cut Designs', 'https://m.media-amazon.com/images/I/317PWpI1OxL.jpg'),
('3', 'Furniture', 'Patio Furniture Set, 4 Pieces', 'Furniture Rattan Chairs and Table Wicker Conversation Set', 'https://m.media-amazon.com/images/I/71hWpBLGuOL._AC_UL320_.jpg'),
('3', 'Furniture', 'KidKraft Wooden Study Desk with Chair', 'Bedroom', 'https://m.media-amazon.com/images/I/71U6qeScffL._AC_SX425_.jpg'),
('3', 'Electronics', 'Apple iPad Air 2 16 GB', 'Silver, Newest Version (Renewed)', 'https://m.media-amazon.com/images/I/41QKpJkq9yS._AC_UL320_.jpg'),
('3', 'Art', 'Apple Pie Poster', 'Yummy', 'https://i.pinimg.com/564x/20/51/3d/20513d6a534af6d260a6f64f4457e8d1.jpg'),
('3', 'Art', 'Classic Bold and Brash Painting', 'Canvas Wall Art Print Home Bathroom Decor Framed', 'https://m.media-amazon.com/images/I/61tyB2MtOcL._AC_UL320_.jpg'),
('4', 'Motors', 'Honda 750 Motorcycle 1992', 'Good Condition',  'https://m.media-amazon.com/images/I/710j1kjJ0GL._AC_SL1200_.jpg'),
('4', 'Motors', 'Tactical Flashtight', 'Rechargeable, 18650, 6PCS 3.7V 9900mAh',  'https://m.media-amazon.com/images/I/61smOeostlL._AC_UL320_.jpg'),
('4', 'Electronics', 'Touch-Screen Smartwatch 3X Games', 'Band - Model: MIN4045AZ',  'https://m.media-amazon.com/images/I/61dfuJcPnEL._AC_UY606_.jpg'),
('4', 'Furniture', 'Outdoor Patio Bistro Set', 'Copper',  'https://images-na.ssl-images-amazon.com/images/I/81DbeTNBDHL._RC%7C81DbeTNBDHL.jpg_SY300_SX300_.jpg'),
('4', 'Motors', 'Vintage White and Blue Speedboat', 'Circa 1971', 'https://image.shutterstock.com/image-photo/plastic-mediterranean-style-boat-adriatic-260nw-5634100.jpg'),
('5', 'Motors', 'Dirt Bike Motorcycle Bike', '5-Speed Manual', 'https://m.media-amazon.com/images/I/61PNESxuL6L._AC_SX425_.jpg'),
('5', 'Motors', 'Adult Gas Motorcycle', 'Water Cooled', 'https://m.media-amazon.com/images/I/61YSNx+w6NS._AC_SX425_.jpg'),
('5', 'Motors', 'Adult Motorcycle', '198cc, 4-stroke, single-cylinder, 6 Speed', 'https://m.media-amazon.com/images/I/61sAYnpYmiL._AC_SX425_.jpg'),
('5', 'Motors', 'Electric Start Kids Dirt Bike', 'Real 2-stroke engine', 'https://m.media-amazon.com/images/I/71wsQbLF07L._AC_SX425_.jpg'),
('5', 'Motors', '350W Brushed Electric Motor', '24 Volts(DC), 350 Watts, 3100RPM', 'https://m.media-amazon.com/images/I/71lvumMGUVL._SX425_.jpg'),
('5', 'Motors', 'Mophorn 3 HP Electric Motor', '115 Volts (AC) , 3 hp, 3450 RPM', 'https://m.media-amazon.com/images/I/61tDklt31KL._AC_SX425_.jpg'),
('5', 'Motors', '12V 160rpm DC Worm Gear Motor', '12V 160rpm', 'https://m.media-amazon.com/images/I/51I86jyHWNL._AC_SX425_.jpg'),
('5', 'Motors', 'DC Reversible Electric Gear Motor', '12V 50rpm', 'https://m.media-amazon.com/images/I/81XY3EQxBWL._SX522_.jpg'),
('5', 'Motors', 'Motor Oil Scented Candle', 'Handmade Products', 'https://m.media-amazon.com/images/I/81pmchAUyfL._SY500_.jpg'),
('5', 'Motors', 'Tesla Car Generations', 'Unframed, Satin Paper', 'https://m.media-amazon.com/images/I/31fCHT9TDkL.jpg'),
('6', 'Art', '118 Piece Deluxe Art Set', 'Acrylic, Multicolor', 'https://m.media-amazon.com/images/I/911WptmMU7S._AC_SX679_.jpg'),
('6', 'Art', 'XL Drawing Set', 'Color: Green, Graphite, Black', 'https://m.media-amazon.com/images/I/51Nq0mBFpjL._AC_.jpg'),
('6', 'Art', '155 Pcs Artist Painting Set', 'for Acrylic, Oil, Watercolor Painting', 'https://m.media-amazon.com/images/I/81NzSe6RUPL._AC_SX679_.jpg'),
('6', 'Art', '85 Piece Art Set', 'Color: Brown, Acrylic, Multicolor', 'https://images-na.ssl-images-amazon.com/images/I/812GICDiZyL.__AC_SX300_SY300_QL70_FMwebp_.jpg'),
('6', 'Art', 'Blue Beach Wall-Art', 'Color: Blue, Canvas wall art, 14" x 14" x 4PCS', 'https://m.media-amazon.com/images/I/91o-JCneSaS._AC_SX679_.jpg'),
('6', 'Art', 'Framed Canvas Wall Art Set', 'Color: Natural, Canvas, 2Piece 18 x 24, Transitional', 'https://m.media-amazon.com/images/I/81Oa2KPx2kL._AC_SX679_.jpg'),
('6', 'Art', 'Sigma Art Lens for Canon', '24-70mm F2.8, Wkde Angle, Canon EF', 'https://m.media-amazon.com/images/I/71kltHdtE9L._AC_SX425_.jpg'),
('6', 'Art', 'Sigma Art DG HSM Lens', 'Telephoto 9 135mm', 'https://m.media-amazon.com/images/I/51YvamItiGL._AC_SX425_.jpg'),
('6', 'Art', 'Watercolor Black Map World', 'Cotton Canvas, Pine Wooden Frame', 'https://m.media-amazon.com/images/I/81Mw2ar72fL._SY500_.jpg'),
('6', 'Art', 'World Map Canvas Wall Art', 'Rust World Map, Canvas', 'https://m.media-amazon.com/images/I/81LGpiINtIL._AC_SX679_.jpg'),
('7', 'Beauty', 'Foundation Liquid Makeup', 'Not Tested On Animals, Reduces Redness, Hypoallergenic, Natural Ingredients, Radiant Finish', 'https://m.media-amazon.com/images/I/71PVhmJzrJL._SX425_.jpg'),
('7', 'Beauty', '5 Pcs Makeup Sponge Set', '5pcs multi-colored sponges', 'https://m.media-amazon.com/images/I/71UA-uPK-FL._SX425_.jpg'),
('7', 'Beauty', '3-in-1 Detox Mud Mask', 'Skin Type: All, Detoxifying, Unscented', 'https://m.media-amazon.com/images/I/51m46NYOFCL._SX425_.jpg'),
('7', 'Beauty', 'Colgate Total Whitening Toothpaste', '4.8 Oz (Pack of 4)', 'https://m.media-amazon.com/images/I/915O4117YPL._SX425_.jpg'),
('7', 'Beauty', 'Hair Dryer and Hot Air Brush', 'Hair Type: All, Color: Black', 'https://m.media-amazon.com/images/I/71GIRogtyNL._SX425_.jpg'),
('7', 'Beauty', 'Makeup Brush Cleaner Dryer', 'Color: Black, Skin Tone: All', 'https://m.media-amazon.com/images/I/71fKrMESl4L._SX425_.jpg'),
('7', 'Beauty', 'Facial Spray with Aloe', 'Scent: Aloe Vera, Spray', 'https://m.media-amazon.com/images/I/71Jip8HttkL._SX522_.jpg'),
('7', 'Beauty', 'Butt Cream And Serum Set!', 'Firming, Skin Type: All', 'https://m.media-amazon.com/images/I/61fCZgJM7JL._SX425_.jpg'),
('7', 'Beauty', 'SKIN PERFECTING', 'Unscented, Exfoliating', 'https://m.media-amazon.com/images/I/61L0IlgrfzL._SY879_.jpg'),
('7', 'Beauty', 'Dermalogica Skin Cleanser', 'Item Form: oil, Scent: Rose, ', 'https://m.media-amazon.com/images/I/615NNrZdh5L._SX522_.jpg'),
('7', 'Beauty', 'Sun Shield Liquid', 'Unscented, 50 SPF, Skin Type: Normal', 'https://m.media-amazon.com/images/I/51jgBfDNNkS._SX425_.jpg'),
('8', 'Toys', 'Kids Bow and Arrow Set', 'LED Light, Green, Arrow, Right Hand', 'https://m.media-amazon.com/images/I/71xzZpt0DyL._AC_SX522_.jpg'),
('8', 'Toys', 'Crystal Flyers Starlight Idol', 'Color: Crystal Pop Star, Age Range: 6+', 'https://m.media-amazon.com/images/I/81XrcvPPslL._AC_SX522_.jpg'),
('8', 'Toys', 'FUN LITTLE TOYS Toy Boat', '4 mini cars', 'https://m.media-amazon.com/images/I/71NwZv22BSL._AC_SX522_.jpg'),
('8', 'Toys', '(50 Pcs) Fidget Toys', 'Color: Multicolor, Large, Silicone, Creativity', 'https://m.media-amazon.com/images/I/91HcZgWYNzL._AC_SX522_.jpg'),
('8', 'Toys', 'Bubble Lawn Mower for Kids', 'Lawn mower toy', 'https://m.media-amazon.com/images/I/71Zvn0rRMwL._AC_SX522_.jpg'),
('8', 'Toys', 'Toy Rocket Launcher for kids', 'Toddler, Kid', 'https://m.media-amazon.com/images/I/81o39uHgjvL._AC_SX425_.jpg'),
('8', 'Toys', '236 PCS Construction Race Tracks', 'Engineering Construction toys, No Electric', 'https://m.media-amazon.com/images/I/813Txvn-Q+L._AC_SX522_.jpg'),
('8', 'Toys', 'Baby Musical Mats', '25 Music Sounds, Todddler, Kid', 'https://m.media-amazon.com/images/I/71AVqI+QZsL._AC_SX522_.jpg'),
('8', 'Toys', 'Dinosaur Toys for Kids', 'Dinosaurs, Kid 3-5', 'https://m.media-amazon.com/images/I/81CuTrcBlyL._AC_SX522_.jpg'),
('9', 'Clothing', 'Harry Potter Herbology Plants T-Shirt', 'Men & Women', 'https://m.media-amazon.com/images/I/B1OGJ8t+8ZS._CLa%7C2140%2C2000%7CA1yIxU5%2BUdL.png%7C0%2C0%2C2140%2C2000%2B0.0%2C0.0%2C2140.0%2C2000.0_AC_UX425_.png'),
('9', 'Clothing', 'Baby 5 Pack Short Sleeve Bodysuits', '60% Cotton, 37% Polyester, 3% Spandex', 'https://m.media-amazon.com/images/I/713OyKYeUQL._AC_UX466_.jpg'),
('9', 'Clothing', 'Champion Boys and Girls Clothes', '100% Cotton, Machine Wash', 'https://m.media-amazon.com/images/I/81SEi7CRU9L._AC_UX522_.jpg'),
('9', 'Clothing', 'The Drop Women''s Midi Dress', 'Lining: 100% Cotton, Machine Wash', 'https://m.media-amazon.com/images/I/71hUUg+UoyL._AC_UY500_.jpg'),
('9', 'Clothing', 'Summer Women''s Pleated Blouses', '100% Polyester', 'https://m.media-amazon.com/images/I/81IDKTD9KPL._AC_UY500_.jpg'),
('9', 'Clothing', 'Women''s HeatGear Racer Tank', '100% Cotton', 'https://m.media-amazon.com/images/I/818-rqfal7L._AC_SY550_.jpg'),
('9', 'Clothing', 'Kenneth Cole REACTION Men''s Dress Shirt Slim Fit Stretch Collar Non Iron Solid', '100% Cotton', 'https://m.media-amazon.com/images/I/71DMrG9nLRL._AC_UY500_.jpg'),
('9', 'Clothing', 'Double Row Clothing Rack', 'Black, Gun Metal Grey, Metal', 'https://m.media-amazon.com/images/I/91TqDzCLhLL._SY500_.jpg'),
('9', 'Clothing', 'adidas Originals Men''s Shoes', '100% Leather', 'https://m.media-amazon.com/images/I/61HtHA4dJVL._AC_UY500_.jpg'),
('9', 'Clothing', 'Boys'' Shirt Half-Zip Pullover', '100% Cotton', 'https://m.media-amazon.com/images/I/71JaJE6j5DL._AC_UX522_.jpg'),
('10', 'Home', 'Balinese Hanging Home Décor Coastal', 'Brown, Reclaimed Teak wood', 'https://m.media-amazon.com/images/I/91LYxyL0YkL._SY500_.jpg'),
('10', 'Home', 'Mandala Wood Home Decor', 'Color: Turquoise and Gold', 'https://m.media-amazon.com/images/I/61K0HkMsrjL._SX500_.jpg'),
('10', 'Home', 'Home Sweet Home Dish Towel', '16”x24” Waffle Weave Kitchen Towel', 'https://m.media-amazon.com/images/I/719AD78TJuL._SX500_.jpg'),
('10', 'Home', 'New 17 pcs Kitchen Knife Set', 'Black, Stainless Steel', 'https://m.media-amazon.com/images/I/91931AxlUPL._AC_SX679_.jpg'),
('10', 'Home', 'Pot Strainer and Pasta Strainer', 'Silicone, Adjustable, Clip On Strainer', 'https://m.media-amazon.com/images/I/61Wt0QY-adL._AC_SX679_.jpg'),
('10', 'Home', 'Mop Broom Holder Wall Hanger', 'Black, Metal, Rubber', 'https://m.media-amazon.com/images/I/71UJW6pRP2L._AC_SX679_.jpg'),
('10', 'Home', 'Air Purifiers for Home', 'AC / DC', 'https://m.media-amazon.com/images/I/71YBZCYwH2L._AC_SX679_.jpg'),
('10', 'Home', 'Home Wall Decor Letter', 'Age Range: Kid', 'https://m.media-amazon.com/images/I/61z7qaiPJ7L._AC_SX679_.jpg'),
('10', 'Home', 'Over the Sink Colander Strainer Basket', 'Modern, Adjustable', 'https://m.media-amazon.com/images/I/710HekWxw4L._AC_SX679_.jpg'),
('10', 'Home', 'Floating Shelves for Wall Set Towel Rack', 'Wall Mount, Office, Kitchen, Bathroom, Bedroom, Living Room', 'https://m.media-amazon.com/images/I/71ynLqD9--L._AC_SX679_.jpg');
